import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { calculateAllScores, getCareerRecommendation } from '../utils/scoreCalculator';
import { careerDatabase, collegeDatabase } from '../utils/careerDatabase';
import { sendReportByEmail } from '../utils/emailService';

function Dashboard() {
  const navigate = useNavigate();
  const [scores, setScores] = useState(null);
  const [career, setCareer] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedCareer, setSelectedCareer] = useState(null);
  const [showCareerDetails, setShowCareerDetails] = useState(false);
  const [emailSent, setEmailSent] = useState(false);
  const [sendingEmail, setSendingEmail] = useState(false);
  const [userEmail, setUserEmail] = useState('');

  useEffect(() => {
    const calculatedScores = calculateAllScores();
    const careerMatch = getCareerRecommendation(calculatedScores);
    setScores(calculatedScores);
    setCareer(careerMatch);
    setLoading(false);
  }, []);

  const getCareerDetails = (careerName) => {
    const details = careerDatabase[careerName] || careerDatabase["Software Engineer"];
    setSelectedCareer(details);
    setShowCareerDetails(true);
  };

  const downloadPDF = () => {
    const date = new Date().toLocaleDateString();
    const userName = localStorage.getItem('userName') || 'User';
    
    const reportContent = `
╔══════════════════════════════════════════════════════════════╗
║                 CAREER ASSESSMENT REPORT                     ║
║                       Generated by                           ║
║              Career Assessment System                        ║
╚══════════════════════════════════════════════════════════════╝

Report Generated: ${date}
User: ${userName}

═══════════════════════════════════════════════════════════════

📌 YOUR TOP CAREER MATCH: ${career.career}
   Match Score: ${career.match}%
   Industry: ${career.industry}
   Growth Projection: ${career.growth}

═══════════════════════════════════════════════════════════════

📊 YOUR ASSESSMENT SCORES:

   • Aptitude & Logic:        ${scores.aptitude}/100
   • Creativity & Expression: ${scores.creativity}/100
   • Commerce & Finance:      ${scores.commerce}/100
   • Leadership & People:     ${scores.leadership}/100

═══════════════════════════════════════════════════════════════

🎓 CAREER DETAILS:

${selectedCareer ? `
Salary Range:
   Entry Level: ${selectedCareer.salary.entry}
   Mid Level: ${selectedCareer.salary.mid}
   Senior Level: ${selectedCareer.salary.senior}
   Global Average: ${selectedCareer.salary.global}

Required Education:
   ${selectedCareer.education}

Top Companies Hiring:
   ${selectedCareer.companies.join(', ')}

Daily Tasks:
   ${selectedCareer.dailyTasks.map(t => `   • ${t}`).join('\n   ')}

Skills Required:
   ${selectedCareer.skills.map(s => `   • ${s}`).join('\n   ')}

Career Growth:
   ${selectedCareer.growth}

Resources to Learn:
   ${selectedCareer.resources.map(r => `   • ${r.name}: ${r.link}`).join('\n   ')}
` : 'Click on "View Career Details" to see detailed information.'}

═══════════════════════════════════════════════════════════════

🏛️ COLLEGE RECOMMENDATIONS:

${(() => {
  const stream = career.career.includes('Software') || career.career.includes('Data') ? 'Science (PCM)' :
                  career.career.includes('Creative') || career.career.includes('Design') ? 'Arts & Humanities' :
                  career.career.includes('Business') ? 'Commerce' : 'Science (PCM)';
  const colleges = collegeDatabase[stream] || collegeDatabase['Science (PCM)'];
  return `
TOP COLLEGES IN INDIA:
${colleges.india.map(c => `   • ${c.name} - ${c.location} (${c.ranking})`).join('\n')}

TOP COLLEGES ABROAD:
${colleges.abroad.map(c => `   • ${c.name} - ${c.location} (${c.ranking})`).join('\n')}
`;
})()}

═══════════════════════════════════════════════════════════════

📅 5-YEAR ACTION PLAN:

   YEAR 1 (11th Grade):
   • Complete 11th with focus on core subjects
   • Start building foundational knowledge
   • Participate in relevant workshops

   YEAR 2 (12th Grade):
   • Score well in board exams (85%+)
   • Prepare for entrance exams
   • Build portfolio of projects

   YEAR 3 (1st Year College):
   • Start undergraduate degree
   • Learn fundamentals of your field
   • Join student clubs and societies

   YEAR 4 (2nd Year College):
   • Take specialized courses
   • Start internships
   • Work on real-world projects

   YEAR 5 (3rd Year + Beyond):
   • Complete degree with good grades
   • Secure job or higher studies
   • Begin professional career

═══════════════════════════════════════════════════════════════

💡 SKILLS TO DEVELOP:

   ${scores.aptitude < 70 ? '✓ Logical Reasoning' : '✓ Problem Solving (Strengthened)'}
   ${scores.creativity < 70 ? '✓ Creative Thinking' : '✓ Creative Expression (Strengthened)'}
   ${scores.commerce < 70 ? '✓ Financial Literacy' : '✓ Business Acumen (Strengthened)'}
   ${scores.leadership < 70 ? '✓ Leadership & Communication' : '✓ People Management (Strengthened)'}

═══════════════════════════════════════════════════════════════

🔄 ALTERNATE CAREER PATHS:

   • Data Analyst - Use data to drive business decisions
   • UX Designer - Create intuitive user experiences
   • Business Consultant - Help organizations improve performance

═══════════════════════════════════════════════════════════════

This report is generated by Career Assessment System.
For more details, visit: https://career-assessment-frontend-ten.vercel.app
`;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Career_Report_${userName}_${date.replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSendEmail = async () => {
    if (!userEmail) {
      alert('Please enter your email address');
      return;
    }
    setSendingEmail(true);
    const result = await sendReportByEmail(userEmail, localStorage.getItem('userName') || 'User', scores, career, roadmapPreview);
    setEmailSent(true);
    setSendingEmail(false);
    alert(result.message);
  };

  if (loading) {
    return (
      <div style={styles.loadingContainer}>
        <div className="loader"></div>
        <p>Loading your results...</p>
      </div>
    );
  }

  const scoreCategories = [
    { name: 'Aptitude & Logic', value: scores.aptitude, icon: '🧠', color: '#a855f7', description: 'Problem solving, analytical thinking, logical reasoning' },
    { name: 'Creativity & Expression', value: scores.creativity, icon: '🎨', color: '#ec4899', description: 'Creative thinking, artistic expression, innovation' },
    { name: 'Commerce & Finance', value: scores.commerce, icon: '📊', color: '#f59e0b', description: 'Business acumen, financial understanding, numerical ability' },
    { name: 'Leadership & People', value: scores.leadership, icon: '👥', color: '#10b981', description: 'Team management, communication, influencing skills' }
  ];

  const alternateCareers = [
    { icon: '📊', title: 'Data Analyst', desc: 'Use data to drive business decisions', salary: '₹4-8 LPA' },
    { icon: '🎨', title: 'UX Designer', desc: 'Create intuitive user experiences', salary: '₹5-10 LPA' },
    { icon: '📈', title: 'Business Consultant', desc: 'Help organizations improve performance', salary: '₹8-15 LPA' }
  ];

  const roadmapPreview = [
    { year: 'Year 1', tasks: ['Complete 11th with focus on core subjects'] },
    { year: 'Year 2', tasks: ['Score well in board exams & entrance tests'] },
    { year: 'Year 3', tasks: ['Start undergraduate degree in your field'] },
    { year: 'Year 4', tasks: ['Take internships and build portfolio'] },
    { year: 'Year 5', tasks: ['Graduate and start professional career'] }
  ];

  const careerDetails = careerDatabase[career.career] || careerDatabase["Software Engineer"];

  return (
    <div style={styles.container}>
      <div style={styles.header}>
        <span style={styles.step}>STEP 8 OF 8</span>
        <h1 style={styles.title}>Interactive Career Dashboard</h1>
        <p style={styles.subtitle}>Personalized insights based on your assessment answers</p>
        <div style={styles.buttonGroup}>
          <button onClick={downloadPDF} style={styles.downloadButton}>
            📄 Download Report (PDF)
          </button>
          <div style={styles.emailSection}>
            <input
              type="email"
              placeholder="Enter your email"
              value={userEmail}
              onChange={(e) => setUserEmail(e.target.value)}
              style={styles.emailInput}
            />
            <button onClick={handleSendEmail} style={styles.emailButton} disabled={sendingEmail}>
              {sendingEmail ? 'Sending...' : '📧 Send Report'}
            </button>
          </div>
        </div>
        {emailSent && <p style={styles.successMsg}>✓ Report sent to your email!</p>}
      </div>

      {/* Top Career Match Card */}
      <div style={styles.matchCard}>
        <div style={styles.matchBadge}>✨ YOUR TOP CAREER MATCH</div>
        <h2 style={styles.careerName}>{career.career}</h2>
        <div style={styles.matchPercentage}>
          <span style={styles.percentageNumber}>{career.match}%</span>
          <span style={styles.percentageLabel}>Match Score</span>
        </div>
        <div style={styles.industryTag}>{career.industry}</div>
        <div style={styles.growthTag}>📈 {career.growth} Growth Projected</div>
        <p style={styles.description}>{career.description}</p>
        <button onClick={() => getCareerDetails(career.career)} style={styles.detailsButton}>
          View Detailed Career Profile →
        </button>
      </div>

      {/* Career Details Modal */}
      {showCareerDetails && selectedCareer && (
        <div style={styles.modalOverlay} onClick={() => setShowCareerDetails(false)}>
          <div style={styles.modal} onClick={(e) => e.stopPropagation()}>
            <button style={styles.closeButton} onClick={() => setShowCareerDetails(false)}>✕</button>
            <h2 style={styles.modalTitle}>{selectedCareer.title}</h2>
            
            <div style={styles.modalSection}>
              <h3>💰 Salary Range</h3>
              <p>Entry: {selectedCareer.salary.entry}</p>
              <p>Mid: {selectedCareer.salary.mid}</p>
              <p>Senior: {selectedCareer.salary.senior}</p>
              <p>Global: {selectedCareer.salary.global}</p>
            </div>

            <div style={styles.modalSection}>
              <h3>🎓 Required Education</h3>
              <p>{selectedCareer.education}</p>
            </div>

            <div style={styles.modalSection}>
              <h3>🏢 Top Companies</h3>
              <div style={styles.companyList}>
                {selectedCareer.companies.map((company, i) => (
                  <span key={i} style={styles.companyTag}>{company}</span>
                ))}
              </div>
            </div>

            <div style={styles.modalSection}>
              <h3>📋 Daily Tasks</h3>
              <ul>
                {selectedCareer.dailyTasks.map((task, i) => (
                  <li key={i}>{task}</li>
                ))}
              </ul>
            </div>

            <div style={styles.modalSection}>
              <h3>⚡ Skills Required</h3>
              <div style={styles.skillList}>
                {selectedCareer.skills.map((skill, i) => (
                  <span key={i} style={styles.skillTag}>{skill}</span>
                ))}
              </div>
            </div>

            <div style={styles.modalSection}>
              <h3>📈 Career Growth</h3>
              <p>{selectedCareer.growth}</p>
            </div>

            <div style={styles.modalSection}>
              <h3>📚 Learning Resources</h3>
              {selectedCareer.resources.map((resource, i) => (
                <div key={i} style={styles.resourceLink}>
                  <a href={resource.link} target="_blank" rel="noopener noreferrer">
                    {resource.type === 'course' ? '📘' : resource.type === 'video' ? '🎥' : '🌐'} {resource.name}
                  </a>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Score Cards Grid */}
      <h3 style={styles.sectionTitle}>Your Assessment Scores</h3>
      <div style={styles.scoreGrid}>
        {scoreCategories.map((cat, idx) => (
          <div key={idx} style={styles.scoreCard}>
            <div style={styles.scoreIcon}>{cat.icon}</div>
            <div style={styles.scoreInfo}>
              <div style={styles.scoreName}>{cat.name}</div>
              <div style={styles.scoreValue}>{cat.value}/100</div>
              <div style={styles.scoreBar}>
                <div style={{...styles.scoreFill, width: `${cat.value}%`, background: cat.color}}></div>
              </div>
              <div style={styles.scoreDesc}>{cat.description}</div>
            </div>
          </div>
        ))}
      </div>

      {/* College Recommendations */}
      <h3 style={styles.sectionTitle}>🎓 Top College Recommendations</h3>
      <div style={styles.collegeSection}>
        <div style={styles.collegeCard}>
          <h4>🇮🇳 Top Colleges in India</h4>
          {(() => {
            const stream = career.career.includes('Software') || career.career.includes('Data') ? 'Science (PCM)' :
                          career.career.includes('Creative') || career.career.includes('Design') ? 'Arts & Humanities' :
                          career.career.includes('Business') ? 'Commerce' : 'Science (PCM)';
            const colleges = collegeDatabase[stream] || collegeDatabase['Science (PCM)'];
            return colleges.india.slice(0, 3).map((college, i) => (
              <div key={i} style={styles.collegeItem}>
                <strong>{college.name}</strong> - {college.location} ({college.ranking})
              </div>
            ));
          })()}
        </div>
        <div style={styles.collegeCard}>
          <h4>🌍 Top Colleges Abroad</h4>
          {(() => {
            const stream = career.career.includes('Software') || career.career.includes('Data') ? 'Science (PCM)' :
                          career.career.includes('Creative') || career.career.includes('Design') ? 'Arts & Humanities' :
                          career.career.includes('Business') ? 'Commerce' : 'Science (PCM)';
            const colleges = collegeDatabase[stream] || collegeDatabase['Science (PCM)'];
            return colleges.abroad.slice(0, 3).map((college, i) => (
              <div key={i} style={styles.collegeItem}>
                <strong>{college.name}</strong> - {college.location} ({college.ranking})
              </div>
            ));
          })()}
        </div>
      </div>

      {/* Skills to Develop */}
      <h3 style={styles.sectionTitle}>💪 Skills to Develop</h3>
      <div style={styles.skillsContainer}>
        {scores.aptitude < 70 && <span style={styles.skillTag}>🔍 Logical Reasoning</span>}
        {scores.creativity < 70 && <span style={styles.skillTag}>🎨 Creative Thinking</span>}
        {scores.commerce < 70 && <span style={styles.skillTag}>📊 Financial Literacy</span>}
        {scores.leadership < 70 && <span style={styles.skillTag}>👥 Leadership & Communication</span>}
        {scores.aptitude >= 70 && <span style={styles.skillTag}>✅ Problem Solving (Strengthened)</span>}
        {scores.creativity >= 70 && <span style={styles.skillTag}>✅ Creative Expression (Strengthened)</span>}
      </div>

      {/* Career Resources */}
      <h3 style={styles.sectionTitle}>📚 Career Resources</h3>
      <div style={styles.resourcesContainer}>
        {careerDetails.resources.slice(0, 3).map((resource, i) => (
          <div key={i} style={styles.resourceCard}>
            <span style={styles.resourceIcon}>{resource.type === 'course' ? '📘' : resource.type === 'video' ? '🎥' : '🌐'}</span>
            <div>
              <div style={styles.resourceTitle}>{resource.name}</div>
              <a href={resource.link} target="_blank" rel="noopener noreferrer" style={styles.resourceLink}>
                Access Resource →
              </a>
            </div>
          </div>
        ))}
      </div>

      {/* 5-Year Roadmap Preview */}
      <h3 style={styles.sectionTitle}>📅 Your 5-Year Action Plan</h3>
      <div style={styles.roadmapContainer}>
        {roadmapPreview.map((item, idx) => (
          <div key={idx} style={styles.roadmapItem}>
            <div style={styles.roadmapYear}>{item.year}</div>
            <div style={styles.roadmapTask}>{item.tasks[0]}</div>
          </div>
        ))}
      </div>
      <button onClick={() => navigate('/roadmap')} style={styles.viewRoadmapButton}>
        View Full Detailed Roadmap →
      </button>

      {/* Alternate Careers - 3 Cards */}
      <h3 style={styles.sectionTitle}>🔄 Alternative Career Paths</h3>
      <div style={styles.alternateContainer}>
        {alternateCareers.map((item, idx) => (
          <div key={idx} style={styles.alternateCard}>
            <span style={styles.alternateIcon}>{item.icon}</span>
            <div style={styles.alternateContent}>
              <div style={styles.alternateTitle}>{item.title}</div>
              <div style={styles.alternateDesc}>{item.desc}</div>
              <div style={styles.alternateSalary}>{item.salary}</div>
            </div>
          </div>
        ))}
      </div>

      <button onClick={() => navigate('/profile')} style={styles.startNewButton}>
        Start New Assessment →
      </button>
    </div>
  );
}

const styles = {
  container: { maxWidth: '1100px', margin: '2rem auto', padding: '2rem' },
  loadingContainer: { textAlign: 'center', marginTop: '4rem', color: 'white' },
  header: { marginBottom: '2rem', textAlign: 'center' },
  step: { color: '#a855f7', fontSize: '0.9rem', fontWeight: '600', display: 'block', marginBottom: '0.5rem' },
  title: { fontSize: '2rem', textAlign: 'center', color: 'white', marginBottom: '0.5rem' },
  subtitle: { textAlign: 'center', color: '#aaa', marginBottom: '1rem' },
  buttonGroup: { display: 'flex', justifyContent: 'center', gap: '1rem', flexWrap: 'wrap', marginBottom: '1rem' },
  downloadButton: { padding: '0.6rem 1.2rem', background: 'rgba(168,85,247,0.2)', border: '1px solid rgba(168,85,247,0.5)', borderRadius: '8px', color: '#a855f7', cursor: 'pointer', fontSize: '0.9rem' },
  emailSection: { display: 'flex', gap: '0.5rem' },
  emailInput: { padding: '0.6rem 1rem', background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '8px', color: 'white', width: '200px' },
  emailButton: { padding: '0.6rem 1.2rem', background: 'linear-gradient(135deg, #a855f7, #4f46e5)', border: 'none', borderRadius: '8px', color: 'white', cursor: 'pointer' },
  successMsg: { color: '#10b981', fontSize: '0.8rem', marginTop: '0.5rem' },
  matchCard: { background: 'rgba(255, 255, 255, 0.08)', borderRadius: '20px', padding: '2rem', textAlign: 'center', marginBottom: '2rem', border: '1px solid rgba(168,85,247,0.3)' },
  matchBadge: { color: '#a855f7', fontSize: '0.8rem', fontWeight: '600', marginBottom: '0.5rem' },
  careerName: { fontSize: '2rem', color: 'white', marginBottom: '1rem' },
  matchPercentage: { marginBottom: '1rem' },
  percentageNumber: { fontSize: '3rem', fontWeight: 'bold', color: '#a855f7' },
  percentageLabel: { fontSize: '0.9rem', color: '#aaa', marginLeft: '0.5rem' },
  industryTag: { display: 'inline-block', padding: '0.3rem 1rem', background: 'rgba(168,85,247,0.2)', borderRadius: '20px', color: '#a855f7', fontSize: '0.8rem', marginBottom: '0.5rem' },
  growthTag: { color: '#10b981', fontSize: '0.9rem', marginBottom: '1rem' },
  description: { color: '#ccc', lineHeight: '1.6' },
  detailsButton: { marginTop: '1rem', padding: '0.5rem 1rem', background: 'rgba(168,85,247,0.3)', border: 'none', borderRadius: '8px', color: '#a855f7', cursor: 'pointer' },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.8)', zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '2rem' },
  modal: { background: '#1e1e2f', maxWidth: '600px', width: '100%', maxHeight: '80vh', overflowY: 'auto', borderRadius: '20px', padding: '2rem', position: 'relative' },
  closeButton: { position: 'absolute', top: '1rem', right: '1rem', background: 'none', border: 'none', color: 'white', fontSize: '1.2rem', cursor: 'pointer' },
  modalTitle: { fontSize: '1.5rem', marginBottom: '1rem', color: 'white' },
  modalSection: { marginBottom: '1.5rem', borderBottom: '1px solid rgba(255,255,255,0.1)', paddingBottom: '1rem' },
  companyList: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '0.5rem' },
  companyTag: { padding: '0.3rem 0.8rem', background: 'rgba(168,85,247,0.2)', borderRadius: '20px', color: '#a855f7', fontSize: '0.8rem' },
  skillList: { display: 'flex', flexWrap: 'wrap', gap: '0.5rem', marginTop: '0.5rem' },
  skillTag: { padding: '0.3rem 0.8rem', background: 'rgba(168,85,247,0.2)', borderRadius: '20px', color: '#a855f7', fontSize: '0.8rem' },
  resourceLink: { marginTop: '0.5rem', color: '#a855f7', textDecoration: 'none' },
  sectionTitle: { fontSize: '1.3rem', color: 'white', marginBottom: '1rem', marginTop: '2rem' },
  scoreGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem', marginBottom: '1rem' },
  scoreCard: { background: 'rgba(255, 255, 255, 0.05)', borderRadius: '12px', padding: '1rem', display: 'flex', alignItems: 'flex-start', gap: '1rem' },
  scoreIcon: { fontSize: '2rem' },
  scoreInfo: { flex: 1 },
  scoreName: { color: '#aaa', fontSize: '0.8rem' },
  scoreValue: { color: 'white', fontSize: '1.2rem', fontWeight: 'bold' },
  scoreBar: { height: '6px', background: 'rgba(255,255,255,0.1)', borderRadius: '3px', marginTop: '0.3rem', marginBottom: '0.3rem' },
  scoreFill: { height: '100%', borderRadius: '3px' },
  scoreDesc: { color: '#666', fontSize: '0.7rem' },
  collegeSection: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1rem', marginBottom: '1rem' },
  collegeCard: { background: 'rgba(255, 255, 255, 0.05)', borderRadius: '12px', padding: '1rem' },
  collegeItem: { padding: '0.5rem', borderBottom: '1px solid rgba(255,255,255,0.1)', fontSize: '0.85rem', color: '#ccc' },
  skillsContainer: { display: 'flex', flexWrap: 'wrap', gap: '0.8rem', marginBottom: '1rem' },
  skillTag: { padding: '0.5rem 1rem', background: 'rgba(168,85,247,0.2)', borderRadius: '20px', color: '#a855f7', fontSize: '0.9rem' },
  resourcesContainer: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem', marginBottom: '1rem' },
  resourceCard: { background: 'rgba(255, 255, 255, 0.05)', borderRadius: '12px', padding: '1rem', display: 'flex', alignItems: 'center', gap: '0.8rem' },
  resourceIcon: { fontSize: '1.5rem' },
  resourceTitle: { color: 'white', fontSize: '0.8rem', fontWeight: 'bold' },
  resourceLink: { color: '#a855f7', fontSize: '0.7rem', textDecoration: 'none' },
  roadmapContainer: { display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: '1rem', marginBottom: '1rem' },
  roadmapItem: { background: 'rgba(255, 255, 255, 0.05)', borderRadius: '10px', padding: '1rem', textAlign: 'center' },
  roadmapYear: { color: '#a855f7', fontWeight: 'bold', marginBottom: '0.5rem', fontSize: '0.9rem' },
  roadmapTask: { color: '#ccc', fontSize: '0.8rem', lineHeight: '1.4' },
  viewRoadmapButton: { width: '100%', padding: '0.8rem', background: 'rgba(168,85,247,0.2)', color: '#a855f7', border: '1px solid rgba(168,85,247,0.3)', borderRadius: '10px', fontSize: '0.9rem', fontWeight: '600', cursor: 'pointer', marginBottom: '1rem' },
  alternateContainer: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1rem', marginBottom: '2rem' },
  alternateCard: { background: 'rgba(255, 255, 255, 0.05)', borderRadius: '12px', padding: '1rem', display: 'flex', alignItems: 'center', gap: '0.8rem' },
  alternateIcon: { fontSize: '1.8rem' },
  alternateContent: { flex: 1 },
  alternateTitle: { color: 'white', fontWeight: 'bold', fontSize: '0.9rem' },
  alternateDesc: { color: '#aaa', fontSize: '0.7rem', marginTop: '0.2rem' },
  alternateSalary: { color: '#10b981', fontSize: '0.7rem', marginTop: '0.2rem' },
  startNewButton: { width: '100%', padding: '1rem', background: 'linear-gradient(135deg, #a855f7, #4f46e5)', color: 'white', border: 'none', borderRadius: '10px', fontSize: '1rem', fontWeight: '600', cursor: 'pointer', marginTop: '1rem' }
};

export default Dashboard;