import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { calculateAllScores, getCareerRecommendation } from '../utils/scoreCalculator';

function Dashboard() {
  const navigate = useNavigate();
  const [scores, setScores] = useState(null);
  const [career, setCareer] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const calculatedScores = calculateAllScores();
    const careerMatch = getCareerRecommendation(calculatedScores);
    setScores(calculatedScores);
    setCareer(careerMatch);
    setLoading(false);
  }, []);

  // Download PDF function
  const downloadPDF = () => {
    const date = new Date().toLocaleDateString();
    const userName = localStorage.getItem('userName') || 'User';
    
    const reportContent = `
╔══════════════════════════════════════════════════════════════╗
║                 CAREER ASSESSMENT REPORT                     ║
║                       Generated by                           ║
║              Career Assessment System                        ║
╚══════════════════════════════════════════════════════════════╝

Report Generated: ${date}
User: ${userName}

═══════════════════════════════════════════════════════════════

📌 YOUR TOP CAREER MATCH: ${career.career}
   Match Score: ${career.match}%
   Industry: ${career.industry}
   Growth Projection: ${career.growth}

═══════════════════════════════════════════════════════════════

📊 YOUR ASSESSMENT SCORES:

   • Aptitude & Logic:        ${scores.aptitude}/100
   • Creativity & Expression: ${scores.creativity}/100
   • Commerce & Finance:      ${scores.commerce}/100
   • Leadership & People:     ${scores.leadership}/100

   Overall Performance: ${Math.round((scores.aptitude + scores.creativity + scores.commerce + scores.leadership) / 4)}/100

═══════════════════════════════════════════════════════════════

🎓 RECOMMENDED STREAM:

   ${career.career.includes('Software') || career.career.includes('Data') ? '🔬 Science with Mathematics (PCM)' : 
     career.career.includes('Creative') || career.career.includes('Design') ? '🎨 Arts & Humanities' :
     career.career.includes('Business') || career.career.includes('Finance') ? '📊 Commerce with Mathematics' :
     career.career.includes('Manager') || career.career.includes('Leader') ? '👥 Humanities / Management' : '🌟 Balanced Stream'}

═══════════════════════════════════════════════════════════════

📅 5-YEAR ACTION PLAN:

   YEAR 1 (11th Grade):
   • Complete 11th with focus on core subjects
   • Start building foundational knowledge
   • Participate in relevant workshops

   YEAR 2 (12th Grade):
   • Score well in board exams (85%+)
   • Prepare for entrance exams
   • Build portfolio of projects

   YEAR 3 (1st Year College):
   • Start undergraduate degree
   • Learn fundamentals of your field
   • Join student clubs and societies

   YEAR 4 (2nd Year College):
   • Take specialized courses
   • Start internships
   • Work on real-world projects

   YEAR 5 (3rd Year + Beyond):
   • Complete degree with good grades
   • Secure job or higher studies
   • Begin professional career

═══════════════════════════════════════════════════════════════

💡 SKILLS TO DEVELOP:

   ${scores.aptitude < 70 ? '✓ Logical Reasoning' : '✓ Problem Solving (Strengthened)'}
   ${scores.creativity < 70 ? '✓ Creative Thinking' : '✓ Creative Expression (Strengthened)'}
   ${scores.commerce < 70 ? '✓ Financial Literacy' : '✓ Business Acumen (Strengthened)'}
   ${scores.leadership < 70 ? '✓ Leadership & Communication' : '✓ People Management (Strengthened)'}

═══════════════════════════════════════════════════════════════

🔄 ALTERNATE CAREER PATHS:

   • Data Analyst - Use data to drive business decisions
   • UX Designer - Create intuitive user experiences
   • Business Consultant - Help organizations improve performance

═══════════════════════════════════════════════════════════════

This report is generated by Career Assessment System.
For more details, visit: https://career-assessment-frontend-ten.vercel.app

`;
    
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Career_Report_${userName}_${date.replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div style={styles.loadingContainer}>
        <div className="loader"></div>
        <p>Loading your results...</p>
      </div>
    );
  }

  const scoreCategories = [
    { name: 'Aptitude & Logic', value: scores.aptitude, icon: '🧠', color: '#a855f7', description: 'Problem solving, analytical thinking, logical reasoning' },
    { name: 'Creativity & Expression', value: scores.creativity, icon: '🎨', color: '#ec4899', description: 'Creative thinking, artistic expression, innovation' },
    { name: 'Commerce & Finance', value: scores.commerce, icon: '📊', color: '#f59e0b', description: 'Business acumen, financial understanding, numerical ability' },
    { name: 'Leadership & People', value: scores.leadership, icon: '👥', color: '#10b981', description: 'Team management, communication, influencing skills' }
  ];

  const alternateCareers = [
    { icon: '📊', title: 'Data Analyst', desc: 'Use data to drive business decisions', salary: '$70k - $120k' },
    { icon: '🎨', title: 'UX Designer', desc: 'Create intuitive user experiences', salary: '$75k - $130k' },
    { icon: '📈', title: 'Business Consultant', desc: 'Help organizations improve performance', salary: '$80k - $150k' }
  ];

  const roadmapPreview = [
    { year: 'Year 1', task: 'Complete 11th with focus on core subjects' },
    { year: 'Year 2', task: 'Score well in board exams & entrance tests' },
    { year: 'Year 3', task: 'Start undergraduate degree in your field' },
    { year: 'Year 4', task: 'Take internships and build portfolio' },
    { year: 'Year 5', task: 'Graduate and start professional career' }
  ];

  return (
    <div style={styles.container}>
      {/* Header with Step Counter */}
      <div style={styles.header}>
        <span style={styles.step}>STEP 8 OF 8</span>
        <h1 style={styles.title}>Interactive Career Dashboard</h1>
        <p style={styles.subtitle}>Personalized insights based on your assessment answers</p>
        <button onClick={downloadPDF} style={styles.downloadButton}>
          📄 Download Report (PDF)
        </button>
      </div>

      {/* Top Career Match Card */}
      <div style={styles.matchCard}>
        <div style={styles.matchBadge}>
          <span>✨ YOUR TOP CAREER MATCH</span>
        </div>
        <h2 style={styles.careerName}>{career.career}</h2>
        <div style={styles.matchPercentage}>
          <span style={styles.percentageNumber}>{career.match}%</span>
          <span style={styles.percentageLabel}>Match Score</span>
        </div>
        <div style={styles.industryTag}>{career.industry}</div>
        <div style={styles.growthTag}>📈 {career.growth} Growth Projected</div>
        <p style={styles.description}>{career.description}</p>
      </div>

      {/* Score Cards Grid */}
      <h3 style={styles.sectionTitle}>Your Assessment Scores</h3>
      <div style={styles.scoreGrid}>
        {scoreCategories.map((cat, idx) => (
          <div key={idx} style={styles.scoreCard}>
            <div style={styles.scoreIcon}>{cat.icon}</div>
            <div style={styles.scoreInfo}>
              <div style={styles.scoreName}>{cat.name}</div>
              <div style={styles.scoreValue}>{cat.value}/100</div>
              <div style={styles.scoreBar}>
                <div style={{...styles.scoreFill, width: `${cat.value}%`, background: cat.color}}></div>
              </div>
              <div style={styles.scoreDesc}>{cat.description}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Skills to Develop */}
      <h3 style={styles.sectionTitle}>Skills to Develop</h3>
      <div style={styles.skillsContainer}>
        {scores.aptitude < 70 && <span style={styles.skillTag}>🔍 Logical Reasoning</span>}
        {scores.creativity < 70 && <span style={styles.skillTag}>🎨 Creative Thinking</span>}
        {scores.commerce < 70 && <span style={styles.skillTag}>📊 Financial Literacy</span>}
        {scores.leadership < 70 && <span style={styles.skillTag}>👥 Leadership & Communication</span>}
        {scores.aptitude >= 70 && <span style={styles.skillTag}>✅ Problem Solving (Strengthened)</span>}
        {scores.creativity >= 70 && <span style={styles.skillTag}>✅ Creative Expression (Strengthened)</span>}
        {scores.commerce >= 70 && <span style={styles.skillTag}>✅ Business Acumen (Strengthened)</span>}
        {scores.leadership >= 70 && <span style={styles.skillTag}>✅ People Management (Strengthened)</span>}
      </div>

      {/* 5-Year Roadmap Preview */}
      <h3 style={styles.sectionTitle}>Your 5-Year Action Plan</h3>
      <div style={styles.roadmapContainer}>
        {roadmapPreview.map((item, idx) => (
          <div key={idx} style={styles.roadmapItem}>
            <div style={styles.roadmapYear}>{item.year}</div>
            <div style={styles.roadmapTask}>{item.task}</div>
          </div>
        ))}
      </div>
      <button onClick={() => navigate('/roadmap')} style={styles.viewRoadmapButton}>
        View Full Detailed Roadmap →
      </button>

      {/* Alternate Careers - 3 Cards */}
      <h3 style={styles.sectionTitle}>Alternative Career Paths</h3>
      <div style={styles.alternateContainer}>
        {alternateCareers.map((item, idx) => (
          <div key={idx} style={styles.alternateCard}>
            <span style={styles.alternateIcon}>{item.icon}</span>
            <div style={styles.alternateContent}>
              <div style={styles.alternateTitle}>{item.title}</div>
              <div style={styles.alternateDesc}>{item.desc}</div>
              <div style={styles.alternateSalary}>{item.salary}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Career Insights */}
      <h3 style={styles.sectionTitle}>Career Insights</h3>
      <div style={styles.insightsContainer}>
        <div style={styles.insightCard}>
          <span style={styles.insightIcon}>💼</span>
          <div>
            <div style={styles.insightTitle}>Job Market Outlook</div>
            <div style={styles.insightText}>The technology and business sectors are expected to grow by 22% in the next 5 years.</div>
          </div>
        </div>
        <div style={styles.insightCard}>
          <span style={styles.insightIcon}>🎓</span>
          <div>
            <div style={styles.insightTitle}>Top Companies Hiring</div>
            <div style={styles.insightText}>Google, Microsoft, Amazon, Deloitte, McKinsey, Infosys, TCS, Wipro</div>
          </div>
        </div>
        <div style={styles.insightCard}>
          <span style={styles.insightIcon}>🌍</span>
          <div>
            <div style={styles.insightTitle}>Global Opportunities</div>
            <div style={styles.insightText}>High demand in USA, Canada, UK, Australia, Singapore, UAE, and India</div>
          </div>
        </div>
      </div>

      <button onClick={() => navigate('/profile')} style={styles.startNewButton}>
        Start New Assessment →
      </button>
    </div>
  );
}

const styles = {
  container: {
    maxWidth: '1100px',
    margin: '2rem auto',
    padding: '2rem'
  },
  loadingContainer: {
    textAlign: 'center',
    marginTop: '4rem',
    color: 'white'
  },
  header: {
    marginBottom: '2rem',
    textAlign: 'center'
  },
  step: {
    color: '#a855f7',
    fontSize: '0.9rem',
    fontWeight: '600',
    display: 'block',
    marginBottom: '0.5rem'
  },
  title: {
    fontSize: '2rem',
    textAlign: 'center',
    color: 'white',
    marginBottom: '0.5rem'
  },
  subtitle: {
    textAlign: 'center',
    color: '#aaa',
    marginBottom: '1rem'
  },
  downloadButton: {
    padding: '0.6rem 1.2rem',
    background: 'rgba(168,85,247,0.2)',
    border: '1px solid rgba(168,85,247,0.5)',
    borderRadius: '8px',
    color: '#a855f7',
    cursor: 'pointer',
    fontSize: '0.9rem',
    marginTop: '0.5rem'
  },
  matchCard: {
    background: 'rgba(255, 255, 255, 0.08)',
    borderRadius: '20px',
    padding: '2rem',
    textAlign: 'center',
    marginBottom: '2rem',
    border: '1px solid rgba(168,85,247,0.3)'
  },
  matchBadge: {
    color: '#a855f7',
    fontSize: '0.8rem',
    fontWeight: '600',
    marginBottom: '0.5rem'
  },
  careerName: {
    fontSize: '2rem',
    color: 'white',
    marginBottom: '1rem'
  },
  matchPercentage: {
    marginBottom: '1rem'
  },
  percentageNumber: {
    fontSize: '3rem',
    fontWeight: 'bold',
    color: '#a855f7'
  },
  percentageLabel: {
    fontSize: '0.9rem',
    color: '#aaa',
    marginLeft: '0.5rem'
  },
  industryTag: {
    display: 'inline-block',
    padding: '0.3rem 1rem',
    background: 'rgba(168,85,247,0.2)',
    borderRadius: '20px',
    color: '#a855f7',
    fontSize: '0.8rem',
    marginBottom: '0.5rem'
  },
  growthTag: {
    color: '#10b981',
    fontSize: '0.9rem',
    marginBottom: '1rem'
  },
  description: {
    color: '#ccc',
    lineHeight: '1.6'
  },
  sectionTitle: {
    fontSize: '1.3rem',
    color: 'white',
    marginBottom: '1rem',
    marginTop: '2rem'
  },
  scoreGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '1rem',
    marginBottom: '1rem'
  },
  scoreCard: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '12px',
    padding: '1rem',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '1rem'
  },
  scoreIcon: {
    fontSize: '2rem'
  },
  scoreInfo: {
    flex: 1
  },
  scoreName: {
    color: '#aaa',
    fontSize: '0.8rem'
  },
  scoreValue: {
    color: 'white',
    fontSize: '1.2rem',
    fontWeight: 'bold'
  },
  scoreBar: {
    height: '6px',
    background: 'rgba(255,255,255,0.1)',
    borderRadius: '3px',
    marginTop: '0.3rem',
    marginBottom: '0.3rem'
  },
  scoreFill: {
    height: '100%',
    borderRadius: '3px'
  },
  scoreDesc: {
    color: '#666',
    fontSize: '0.7rem'
  },
  skillsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.8rem',
    marginBottom: '1rem'
  },
  skillTag: {
    padding: '0.5rem 1rem',
    background: 'rgba(168,85,247,0.2)',
    borderRadius: '20px',
    color: '#a855f7',
    fontSize: '0.9rem'
  },
  roadmapContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: '1rem',
    marginBottom: '1rem'
  },
  roadmapItem: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '10px',
    padding: '1rem',
    textAlign: 'center'
  },
  roadmapYear: {
    color: '#a855f7',
    fontWeight: 'bold',
    marginBottom: '0.5rem',
    fontSize: '0.9rem'
  },
  roadmapTask: {
    color: '#ccc',
    fontSize: '0.8rem',
    lineHeight: '1.4'
  },
  viewRoadmapButton: {
    width: '100%',
    padding: '0.8rem',
    background: 'rgba(168,85,247,0.2)',
    color: '#a855f7',
    border: '1px solid rgba(168,85,247,0.3)',
    borderRadius: '10px',
    fontSize: '0.9rem',
    fontWeight: '600',
    cursor: 'pointer',
    marginBottom: '1rem'
  },
  alternateContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1rem',
    marginBottom: '2rem'
  },
  alternateCard: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '12px',
    padding: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem'
  },
  alternateIcon: {
    fontSize: '1.8rem'
  },
  alternateContent: {
    flex: 1
  },
  alternateTitle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: '0.9rem'
  },
  alternateDesc: {
    color: '#aaa',
    fontSize: '0.7rem',
    marginTop: '0.2rem'
  },
  alternateSalary: {
    color: '#10b981',
    fontSize: '0.7rem',
    marginTop: '0.2rem'
  },
  insightsContainer: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '1rem',
    marginBottom: '2rem'
  },
  insightCard: {
    background: 'rgba(255, 255, 255, 0.05)',
    borderRadius: '12px',
    padding: '1rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.8rem'
  },
  insightIcon: {
    fontSize: '1.5rem'
  },
  insightTitle: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: '0.8rem'
  },
  insightText: {
    color: '#aaa',
    fontSize: '0.7rem',
    marginTop: '0.2rem'
  },
  startNewButton: {
    width: '100%',
    padding: '1rem',
    background: 'linear-gradient(135deg, #a855f7, #4f46e5)',
    color: 'white',
    border: 'none',
    borderRadius: '10px',
    fontSize: '1rem',
    fontWeight: '600',
    cursor: 'pointer',
    marginTop: '1rem'
  }
};

export default Dashboard;